# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Q_mf5fNkSxC7IwR9kwcdMbvqRIe9bXzR
"""

import pandas as pd
import matplotlib.pyplot as plt

#Set the path
data_set = pd.read_csv("/content/iris.data", header=None)

# Printing the row and column
rows, columns = data_set.shape
print(f"Number of rows: {rows}")
print(f"Number of columns: {columns}")

#Printing the last column's values
unique_values_in_the_last_column = data_set.iloc[:, -1].unique()
print("Distinct values of the last column:", unique_values_in_the_last_column)

data = data_set[data_set.iloc[:, -1] == "Iris-setosa"]
rows_of_setosa = len(data)
average = data.iloc[:, 0].mean()
max_column_second = data.iloc[:, 1].max()
min_column_third = data.iloc[:, 2].min()

print(f"\nFor Iris-setosa:")
print(f"Number of rows: {rows_of_setosa}")
print(f"First column's average value: {average}")
print(f"Maximum value found in column second: {max_column_second}")
print(f"Minimum value found in column third: {min_column_third}")

marker_styles = {'Iris-setosa': 's', 'Iris-versicolor': '^', 'Iris-virginica': 'o'}
colors = {'Iris-setosa': 'red', 'Iris-versicolor': 'blue', 'Iris-virginica': 'black'}

#Plotting the scatter points
scatter_setosa = plt.scatter(data_set[data_set.iloc[:, -1] == 'Iris-setosa'].iloc[:, 0], data_set[data_set.iloc[:, -1] == 'Iris-setosa'].iloc[:, 1], c='red', marker='s', s=80, edgecolors='k', label='Iris-setosa')
scatter_versicolor = plt.scatter(data_set[data_set.iloc[:, -1] == 'Iris-versicolor'].iloc[:, 0], data_set[data_set.iloc[:, -1] == 'Iris-versicolor'].iloc[:, 1], c='blue', marker='^', s=80, edgecolors='k', label='Iris-versicolor')
scatter_virginica = plt.scatter(data_set[data_set.iloc[:, -1] == 'Iris-virginica'].iloc[:, 0], data_set[data_set.iloc[:, -1] == 'Iris-virginica'].iloc[:, 1], c='black', marker='o', s=80, edgecolors='k', label='Iris-virginica')

plt.xlabel("First Column")
plt.ylabel("Second Column")
plt.title("Scatter Plot for First and Second Columns")
plt.legend()
plt.show()